### ISSUE TITLE
site is missing language selector

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap-systems-family#4]
For some reason localization is disabled. 

![image](https://user-images.githubusercontent.com/56453501/224072283-4bcf130d-2915-4688-957d-756fc2b93469.png)

Enable localization for `prod`. 

https://github.com/NetAppDocs/ontap-systems-family/blob/main/project.yml#L7

**Comment by netapp-jsnyder** [comment]
Fixed in  CI #11
